## ===== [SETTINGS] ===================================
#

        backend = "glx";
        vsync = true;

#
## ====================================================



## ===== [CORNER RADIUS] ==============================
#

        corner-radius = 10;

        rounded-corners-exclude = [
        	"window_type = 'dock'",
        	"window_type = 'desktop'"
        ];

#
## ====================================================



## ===== [WINDOW OPACITY & BLUR] ======================
#

        opacity-rule = [
        	"85:class_g = 'kitty'",
        	"95:class_g = 'thunar' && focused",
        	"85:class_g = 'thunar' && !focused"
        ];


        blur-method = "dual_kawase";
        blur-size = 7;
        blur-deviation = 3.0;

#
## ====================================================



## ===== [WINDOW ANIMATIONS] ===========================
#

        fading = true;
        fade-in-step = 0.05;
        fade-out-step = 0.05;
        fade-delta = 5;

#
## ====================================================
